### ISSUE TITLE
`etc/eturnal.yml` installed world readable

### ISSUE THREAD

**Issue by paulmenzel** [processone/eturnal#10]
I believe, eturnal’s configuration file `etc/eturnal.yml` is installed world readable.

    $ ls -l eturnal-20201030/etc/eturnal.yml
    -rw-r--r-- 1 eturnprj eturngrp 2102 Sep  9 16:34 eturnal-20201030/etc/eturnal.yml

As it might contain the secret, should it be installed with the mode 640?

**Comment by licaon-kter** [comment]
By whom it is?

**Comment by weiss** [comment]
> As it might contain the secret, should it be installed with the mode 640?

Yes, that would be nicer, so as an admin, that's what I'd do.  Our build/packaging tooling is somewhat limited in that regard, but I'll look into adding some hack(s).

For what it's worth, Debian's official Coturn package installs the configuration file world-readable as well, but I guess you won't buy that as an excuse :wink:
