### ISSUE TITLE
Fails to start with `ERL_EPMD_ADDRESS=127.0.0.1`

### ISSUE THREAD

**Issue by paulmenzel** [processone/eturnal#11]
Setting the environment variable for the *epmd* address to localhost `ERL_EPMD_ADDRESS=127.0.0.1` in the systemd service unit

    Environment=ETURNAL_ETC_PREFIX=/project/eturnal ERL_EPMD_ADDRESS=127.0.0.1

eturnal fails to start with the error below.

    eturnalctl[91982]: Protocol 'inet_tcp': register/listen error: econnrefused

**Comment by paulmenzel** [comment]
*epmd* is not a separate service and should be started by *eturnal*.

**Comment by weiss** [comment]
Sounds like `epmd` fails to start with an `ERL_EPMD_ADDRESS` on your system.  One possible reason would be that IPv6 is disabled in a way that doesn't allow binding to `::1` (which epmd tries to do if you specify an IPv4 listen address, which is the reason we [no longer][1] do that by default).

If this is not the issue: Does `journalctl -u eturnal` show additional output?  Do you get any output when stopping `eturnal` and then calling `ERL_EPMD_ADDRESS=127.0.0.1 epmd -d` manually?

[1]: https://github.com/processone/eturnal/commit/3a65d40818058137ee95e5af07a7701669e691f3

**Comment by paulmenzel** [comment]
> Sounds like `epmd` fails to start with an `ERL_EPMD_ADDRESS` on your system. One possible reason would be that IPv6 is disabled in a way that doesn't allow binding to `::1` (which epmd tries to do if you specify an IPv4 listen address, which is the reason we [no longer](https://github.com/processone/eturnal/commit/3a65d40818058137ee95e5af07a7701669e691f3) do that by default).

Indeed, IPv6 is disabled in our environment.

    $ sysctl net.ipv6.conf.all.disable_ipv6
    net.ipv6.conf.all.disable_ipv6 = 1

**Comment by weiss** [comment]
> `net.ipv6.conf.all.disable_ipv6 = 1`

Yes, this is the setup that lets `epmd` fail: Binding to `INADDR6_ANY` works, binding to `INADDR6_LOOPBACK` doesn't.  On our IPv4-only servers, we disable the IPv6 stack altogether by adding `ipv6.disable_ipv6=1` to the kernel command line.  That way, `epmd` won't attempt to bind to `::1`.  (See also [this posting][1], for example.)

So there's nothing we can do about this; if anything, the problem could be [reported against Erlang/OTP][1].

[1]: https://erlang.org/pipermail/erlang-questions/2016-March/088445.html

**Comment by paulmenzel** [comment]
> So there's nothing we can do about this; if anything, the problem could be [reported against Erlang/OTP](https://github.com/erlang/otp/wiki/Bug-reports).

https://github.com/erlang/otp/issues/4820

**Comment by weiss** [comment]
Seems this will be [fixed][1] in future Erlang/OTP releases.

[1]: https://github.com/erlang/otp/commit/e8c9e121c1b286ecddd572190c2a1fe72adc97bb
