### ISSUE TITLE
Minimal / recommended hosting requirements

### ISSUE THREAD

**Issue by louim** [processone/eturnal#13]
Hey! 

It would be nice to have a minimal / recommended hosting requirement, like the minimum RAM/cpu for the server to work correctly. I know it will usually vary depending on the number of connection, but at least a ballpark estimate would be helpful. 

Thanks

**Comment by licaon-kter** [comment]
Raspberry Pi 1 B, 256Mb ~80 users.

/no joke, but define use case :)

**Comment by louim** [comment]
Thanks for the reply. We're using BigBlueButton and are investigating alternatives to COTURN as our stun / turn server. Probably gonna be serving around ~150 concurrent users. I'm not very familiar with memory requirements for erlang, so that's why I asked.

**Comment by danimo** [comment]
We are running this on a 3 Core, 4 GB VM with no issues. The machine is bored. It used to spike when low on ports, but that's fixed.
