### ISSUE TITLE
systemd service: Evaluate `DynamicUser=true`

### ISSUE THREAD

**Issue by paulmenzel** [processone/eturnal#14]
With the settings below

https://github.com/processone/eturnal/blob/f9168eb70d2a1b8f7f110f4022985adb65175e55/config/eturnal.service#L19-L22

it might make sense to set [`DynamicUser=`](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#DynamicUser=) to `true`, which implicitly also sets `NoNewPrivileges=true`.

**Comment by weiss** [comment]
> it might make sense to set `DynamicUser=` to `true`

We'd need to figure out how to handle the `~/.erlang.cookie` file.  Best solution would be to get rid of using it altogether, but there's [no really nice alternative][1] right now.

Apart from that, eturnal doesn't store any persistent data indeed, at least not yet.

> `ProtectSystem=strict`

eturnal should work fine with `strict`, it's just not supported by older systemd versions, so I'm `full` for compatibility with those.

[1]: https://github.com/erlware/relx/issues/803

**Comment by paulmenzel** [comment]
> > it might make sense to set `DynamicUser=` to `true`
> 
> We'd need to figure out how to handle the `~/.erlang.cookie` file. Best solution would be to get rid of using it altogether, but there's [no really nice alternative](https://github.com/erlware/relx/issues/803) right now.
> 
> Apart from that, eturnal doesn't store any persistent data indeed, at least not yet.

Also, with `LogsDirectory=` removed – it is present in the upstream template –, and the log directory being part of the installation prefix, the log directory needs to be listed in `ReadWritePaths=`.

**Comment by weiss** [comment]
> Apart from that, eturnal doesn't store any persistent data indeed, at least not yet.

However, if we do set `DynamicUser=true` and then need persistent data storage later on, it might not be straightforward to revert that setting, as the systemd unit configuration isn't necessarily replaced on upgrade. Therefore, I think we should rather not apply this to the upstream unit file.
