### ISSUE TITLE
To facilitate rollover, the TURN server SHOULD be able to validate incoming MESSAGE-INTEGRITY tokens based on at least 2 shared secrets at any time.

### ISSUE THREAD

**Issue by jonathantawfik** [processone/eturnal#16]
Point 5.2 in [API For Access To TURN Services](https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00) draft mentions that at least 2 keys should be supported at any time.  I don't see anything about this in the documentation.  Is it already supported.  If not, are there any plans too?

**Comment by weiss** [comment]
It's not supported right now.  The idea of the spec is that clients might cache the credentials for later (re)use, whereas in practice, the clients I've seen just (re-)request new credentials immediately before opening a TURN session, so the rollover window would at least be very small.  However, the window still exists; and I can well imagine setups where clients do cache credentials.  So implementing this would probably be a good idea indeed.

**Comment by weiss** [comment]
eturnal 1.5.0 supports specifying a list of secrets.
