### ISSUE TITLE
Reload certificates on eturnalctl reload

### ISSUE THREAD

**Issue by danimo** [processone/eturnal#17]
Currently, new certificates can only be deployed with a restart. However, a reload should suffice. It seems that reloading the PEM file is already in the code base, but my erlang fu is still not very strong.

**Comment by weiss** [comment]
FTR, there's a shorter command line for reloading certificates:

```
$ eturnalctl eval 'eturnal_app:config_change([],[],[]).'
```

(But neither of them will work with future releases.)
