### ISSUE TITLE
UDP error not handled gracefully

### ISSUE THREAD

**Issue by nako-ruru** [processone/eturnal#23]
the following error occurs occasionally, and then, the clients cannot connect eturnal from then on. that is, I have to restart the server

version: [eturnal-1.8.3-x64.exe](https://eturnal.net/download/windows/eturnal-1.8.3-x64.exe) 

![image](https://user-images.githubusercontent.com/26663548/176980872-0deab5aa-2cb5-434b-8461-e0058dd58e4c.png)

**Comment by weiss** [comment]
The network stack is probably receiving an ICMP unreachable error for that client while trying to send the UDP datagram.  The fact that this stops the listener is a bug (in https://github.com/processone/stun), I'll look into it, thanks.

**Comment by nako-ruru** [comment]
i saw you fixed this problem a few hours ago. thanks for your quick response.

i'm not sure whether you mean you fixed **the problem that the client cannot connect eturnal forever** or/and **the cause of the problem**.

if you haven't fixed latter yet, I think I can give you some information that causes this problem.

steps to reproduce this problem. 
I have several c# webrtc client(offer side),

1. when i open one of my webpage, the webpage will notify the c# client create an offer via websocket, and then the c# client will notify the current webpage create an answer via websocket, this procedure can successfully work
1. when i open another same webpage, the new webpage will notify another c# client to create another offer, and then the c# client will notify the new webpage create another answer via websocket,  this procedure can successfully work as well. 
1. howerver, the step 2 causes the the connection established during step 1 disconnects and the server prints errors and hangs forever.

I tried several times, each time this error occurred

**Comment by nako-ruru** [comment]
> 

I tried coturn and pion/turn as well, both work well in my scenarios

**Comment by weiss** [comment]
The error you've shown above indicates that eturnal tried to send a STUN/TURN response to the client via UDP and got an ICMP unreachable error back from the network stack. eturnal stumbled over this error and stopped both handling this session and accepting new ones. That's the thing I fixed: eturnal will now log a `[notice]` in this case, and continue business as usual.

It's not clear to me why eturnal is receiving that error from the network stack from the problem description you gave now. (Do both clients appear as using the same IP address to eturnal, by the way?) Therefore I'm not sure whether my change will solve (or at least hide) your problem. Maybe Coturn is receiving the same error, and ignoring it does the trick, maybe not.

If you like, I could give you a Windows installer using the current code for testing. If you then still run into the problem, we'd have to take a closer look (by using `loglevel: debug` and/or capturing the UDP traffic with
[Wireshark][1]).

[1]: https://www.wireshark.org/download.html

**Comment by nako-ruru** [comment]
I'm glad testing new windows installer, however, it's a pity that I don't understand protocol of either stun or turn, so I think wireshark wouldn't give us any help.

I'm not sure whether telling you my complicated network environment can help.

I have 5 turn servers, 1 is coturn, 3 are pion/turn, and the rest is the eturnal which I installed recently.
I also have several c# client, all of them in different network(not in LAN)

I force the step 1 uses eturnal only, and step 2 tries to find one turn server by webrtc itself

**Comment by nako-ruru** [comment]
[eturnal.zip](https://github.com/processone/eturnal/files/9038488/eturnal.zip)

**Comment by weiss** [comment]
Thanks for those logs.

> it's a pity that I don't understand protocol of either stun or turn, so I think wireshark wouldn't give us any help.

Wireshark would allow for capturing the traffic into a file which you could then send me.  However, let's first check the behavior of the current code.  You can (temporarily) fetch a new installer [from the web site][1].  Can you reproduce the problem using that version?

[1]: https://eturnal.net/tmp/windows/

**Comment by nako-ruru** [comment]
great!

I installed the new version you provided, and then I cannot reproduce it now
