### ISSUE TITLE
No logs created

### ISSUE THREAD

**Issue by licaon-kter** [processone/eturnal#3]
Debian Buster, armv6, HEAD

Eg. when crashing on #2 it says `{log_dir,<<"/var/log/eturnal">>},` while started by systemd, but there's no file there.

**Comment by weiss** [comment]
The crash on #2 happens very early during startup, after parsing but before applying the configuration, and therefore before initializing the file logging.  So it's not a bug in itself that errors are just written to the standard output at this point.
