### ISSUE TITLE
My servers are being attacked by some bad persons

### ISSUE THREAD

**Issue by nako-ruru** [processone/eturnal#31]
My servers are being attacked by some bad persons, what should I do?

![image](https://user-images.githubusercontent.com/26663548/187057771-b8ca016f-f16c-468f-ab0b-061000fdb9b8.png)

**Comment by licaon-kter** [comment]
Move STUN and TURN to some other ports. XMPP clients will get the info via XEP-0215. The ports can be found if you get scanned, but maybe attackers are just using the well known ports and won't bother.

**Comment by paulmenzel** [comment]
Maybe [fail2ban](https://www.fail2ban.org/) could also be an option?

**Comment by licaon-kter** [comment]
@paulmenzel and separate good vs bad how?

Although that port 22 looks like an attempt to DDOS some other host, reflection attack?
