### ISSUE TITLE
SSL key outdated?

### ISSUE THREAD

**Issue by tarkhil** [processone/eturnal#38]
Err:2 https://deb.eturnal.net stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 194.59.205.169 443]

**Comment by weiss** [comment]
Looks fine to me:

```sh
$ openssl s_client -servername deb.eturnal.net -connect deb.eturnal.net:443 </dev/null 2>/dev/null | openssl x509 -noout -enddate
notAfter=Jun 20 00:30:17 2023 GMT
```

What Debian/distro version are you using?

**Comment by tarkhil** [comment]
Ubuntu 20. Sorry. curl worked fine, apt failed until I've updated certificates.

**Comment by weiss** [comment]
Glad to hear it's working now!

Just for the record, in case someone else has similar issues: A workaround would be switching to <http://deb.eturnal.net>, but https:// is preferable of course.
