### ISSUE TITLE
Oracle/docker-compose

### ISSUE THREAD

**Issue by dmr138** [processone/eturnal#43]
I have an oracle cloud instance running ubuntu and docker I get the following error when I start the container, I have the correct ports open/ingress rules through oracle. Anyone have any ideas what might be causing this?

![Screenshot 2023-07-01 at 4 32 00 PM](https://github.com/processone/eturnal/assets/86209027/92813bf4-8b12-4f82-83e4-1625b36f096f)

**Comment by sando38** [comment]
If this "error" is related to the IPv6 STUN query only, you can safely ignore it, because as far as I know, in default Oracle VMs do not have IPv6 addresses assigned. What is the output of your `docker logs name_of_your_container`?

**Comment by dmr138** [comment]
output:
`Cannot query stun.conversations.im:3478: can't assign requested address
Exec: /opt/eturnal/erts-12.3.1/bin/erlexec -noinput +Bd -boot /opt/eturnal/releases/1.10.1/start -mode embedded -boot_var SYSTEM_LIB_DIR /opt/eturnal/lib -config /opt/eturnal/releases/1.10.1/sys.config -args_file /opt/eturnal/releases/1.10.1/vm.args -erl_epmd_port 3470 -start_epmd false -- foreground
Root: /opt/eturnal
/opt/eturnal`

I am getting proper results from both ice tests now I think (**_relay_** and **_srflx_**) so you may be correct. 

Also I don't believe there is an IPv6 address assigned in Oracle.

I will try to connect this to matrix/synapse now. 

thank you.

**Comment by dmr138** [comment]
Was able to make a successful test video call in element, I think it's working properly. 

Since it is inside docker I am running it with a reduced port range since I had issues accessing it with network--host. Not sure if the smaller port range will have a negative effect overall though.

**Comment by sando38** [comment]
> Was able to make a successful test video call in element, I think it's working properly.

If there is anything else, just come back to us.

> Since it is inside docker I am running it with a reduced port range since I had issues accessing it with network--host. Not sure if the smaller port range will have a negative effect overall though.

No, that usually will not have a negative effect. The port range in a certain way defines the capacity / volume of sessions the TURN server can handle. So the higher the range the more "calls" you can offer simultaneously.
