### ISSUE TITLE
Cannot start eturnal service

### ISSUE THREAD

**Issue by RuiRosado** [processone/eturnal#53]
Hi,
I am trying to start the eturnal service on a Linux CentOS 7 (x86_64, AMD EPYC processor), but not succeeding ...
Seems the error is related to permissions on /dev/log (see attached screenshot).
Any idea how to solve this?
BTW:
# ls -l /dev/log
lrwxrwxrwx 1 root root 28 Sep  6 17:23 /dev/log -> /run/systemd/journal/dev-log

I hope you can help.
Thanks.
Rui Rosado
![error](https://github.com/processone/eturnal/assets/737242/1c77ec23-0c07-4721-8e58-4bb0264c7bbd)

**Comment by weiss** [comment]
We tried to reproduce the issue by installing CentOS 7 but things work just fine here.  It seems your systemd/journald version/setup is different from what I got after installing CentOS 7 and running `yum update`, though.  On my system, the old `systemd-journald.socket` unit is used, which reads `/dev/log` directly.  I.e., `/dev/log` is _not_ a symlink (to `/run/systemd/journal/dev-log`) on a vanilla CentOS 7 system, as far as I can see.  So I'm not quite sure how to reproduce your issue, I'm afraid.

Anyway, what's the output of `ls -l /run/systemd/journal/dev-log`?

**Comment by RuiRosado** [comment]
Thanx, Holger for looking into this. The output of

# ls -l /run/systemd/journal/dev-log
srw-rw---- 1 root mysyslog 0 May  1 15:54 /run/systemd/journal/dev-log

**Comment by weiss** [comment]
Ok, so only processes run by users in the `mysyslog` group are permitted to log messages on your system (quick web search sounds as if that might be a [ConfigServer](https://configserver.com) thing?).  I guess one workaround could be to add `eturnal` to that group, e.g. by calling `systemctl edit eturnal` and entering:

```ini
[Service]
SupplementaryGroups=mysyslog
```

**Comment by RuiRosado** [comment]
That solved our problem!
Thank you for your help, Holger.
Cheers
Rui
