### ISSUE TITLE
Add support for ETURNAL_SECRET_FILE to allow Docker secrets workflow

### ISSUE THREAD

**Issue by glalejos** [processone/eturnal#64]
Hello,

I'm trying to pull out all secrets from a Docker Compose definition (and for that I'm moving to a Docker Stack schema), but I'm struggling with the `ETURNAL_SECRET` environment variable.

This separation could be easily achieved if the eturnal Docker image supported an `ETURNAL_SECRET_FILE` environment variable that pointed to the location of a file which contained the secret.

Thank you,

Guillermo

**Comment by sando38** [comment]
I actually pushed a commit already which should enable it. Will look later if it works. You can give it a try with using the `edge` tag, once the github action workflow ran through.

**Comment by sando38** [comment]
NB: This would be a corresponding `docker run` command:

```bash
docker run \
    --secret eturnal_secret \
    -e ETURNAL_SECRET__FILE='/run/secrets/eturnal_secret' \
  ghcr.io/processone/eturnal:edge
```

**Comment by sando38** [comment]
Thanks for the feedback 👍
