### ISSUE TITLE
please don't set bg wo fg

### ISSUE THREAD

**Issue by 532910** [processone/eturnal#7]
Only bg color is defined in `stylesheet.css`:
```
body {
    background-color: white
```
so it looks bad on my end:
![image](https://user-images.githubusercontent.com/14617699/89165051-a80a5100-d580-11ea-842d-59bdadf1c015.png)

**Comment by weiss** [comment]
Thanks, I removed the background color declaration and hope it looks okay now with your browser's defaults?

**Comment by 532910** [comment]
Yep, looks fine now, thank you!
