### ISSUE TITLE
any plans to support IO_URING on linux ? 

### ISSUE THREAD

**Issue by RavikumarTulugu** [processone/eturnal#80]
Please plan iouring support on linux if not done already. 
Thanks ,

**Comment by weiss** [comment]
The underlying VM ([BEAM][1]) doesn't support `io_uring` so far.  Adding support has been [discussed][2] and [(re)considered just recently][3], but probably won't be available anytime soon.  In theory, we could use custom socket code, but I don't think we want to go that route.

I can well image `io_uring` helping with CPU utilization and throughput, but note that TURN specifically has the problem that each and every packet must be (un)wrapped while relayed (so there's no easy way to perform zero-copy I/O).  I don't have numbers, but I'd assume this to be an even more significant bottleneck for TURN relaying compared to the syscall overhead avoided by `io_uring`.  One way to reduce _this_ bottleneck would be to perform the (un)wrapping within kernel space using [eBPF][4], which would also reduce syscall overhead significantly.  ([Others had the same idea][5], by the way.)  This is on my to-do list, but I can't give you a timeframe, sorry.

[1]: https://en.wikipedia.org/wiki/BEAM_(Erlang_virtual_machine)
[2]: https://erlangforums.com/t/erlang-io-uring-support
[3]: https://erlangforums.com/t/erlang-io-uring-support/765/13
[4]: https://ebpf.io
[5]: https://github.com/pion/turn/pull/360

**Comment by RavikumarTulugu** [comment]
thanks for the detailed explanation. yeah,  ebpf + IO_URING is a killer combo.
